# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Nuxt 3 app to Azure Web App - srai-github-insights

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # ✅ Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Step 2: Set up Node.js (Ensure correct version for Nuxt 3)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use the Node.js version compatible with Nuxt 3
          cache: 'npm'

      # ✅ Step 3: Install & Activate PNPM
      - name: Install PNPM
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          echo "$HOME/.local/bin" >> $GITHUB_PATH  # Add PNPM to PATH
          pnpm --version  # Verify PNPM installation

      # ✅ Step 4: Install dependencies with PNPM
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # ✅ Step 5: Build Nuxt 3 app
      - name: Build Nuxt 3 app
        run: pnpm run build

      # ✅ Step 6: Ensure `.output/` Contains Server Files
      - name: Verify Nuxt Build Output
        run: ls -R .output/

       # ✅ Step : Archive Build Output (Fix for Missing .output/)
      - name: Compress `.output/` for deployment
        run: zip -r output.zip .output/

      # ✅ Step 7: Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ✅ Step 8: Set `NITRO_PRESET=node` in Azure App Service
      - name: Configure Azure App Service Environment Variables
        run: |
          az webapp config appsettings set --resource-group srai-github-reporting --name srai-github-insights --settings NITRO_PRESET=node

      # ✅ Step 9: Set Startup Command for Nuxt Nitro Server
      - name: Set Startup Command in Azure
        run: |
          az webapp config set --resource-group srai-github-reporting --name srai-github-insights --startup-file "node .output/server/index.mjs"

      # ✅ Step 10: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'srai-github-insights'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_e94dfd38811a421eafe5ce4eee13b68b }}
          package: '.output/'  # Deploy Nuxt 3 output directory

      # ✅ Step 11: Restart Azure Web App after deployment
      - name: Restart Azure Web App
        run: az webapp restart --name srai-github-insights --resource-group srai-github-reporting

      # ✅ logs
      - name: Fetch Azure Web App Logs (Only on Failure)
        if: failure()
        run: az webapp log tail --name srai-github-insights --resource-group srai-github-reporting

