# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Nuxt 3 app to Azure Web App - srai-github-insights

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # ✅ Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Step 2: Set up Node.js (Ensure correct version for Nuxt 3)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use the Node.js version compatible with Nuxt 3
          cache: 'pnpm'

      # ✅ Step 3: Install PNPM
      - name: Install PNPM
        run: |
          npm install -g pnpm
          pnpm --version  # Verify PNPM installation

      # ✅ Step 4: Install dependencies with PNPM
      - name: Install dependencies
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      # ✅ Step 5: Build Nuxt 3 app
      - name: Build Nuxt 3 app
        run: pnpm run build

      # ✅ Step 6: Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ✅ Step 7: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'srai-github-insights'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_e94dfd38811a421eafe5ce4eee13b68b }}
          package: '.output/'  # Deploy Nuxt 3 output directory

      # ✅ Step 8: Restart Azure Web App after deployment
      - name: Restart Azure Web App
        run: az webapp restart --name srai-github-insights --resource-group srai-github-reporting
